### PR TITLE
Feature/cassandra cdc

### PR DESCRIPTION
**Pull request by stheppi**
This change is [Reviewable](https://reviewable.io/reviews/landoop/stream-reactor/236)

### CODE REVIEW

**Comment by criccomini** [comment]
Are these .class files supposed to be in the PR?

**Comment by stheppi** [comment]
those were removed. (they have the red square in front)

**Comment by criccomini** [comment]
Changes to key struct look good to me.

**Comment by criccomini** [comment]
Checking in on status of this. Are you planning to merge it in>

**Comment by mviamari** [comment]
Is this feature still under development? This would be very useful for a project I'm working on, but it appears quite of date compared to the master branch of this repo.

**Comment by andrewstevenson** [comment]
@mviamari I aren't working on this anymore as the implementation on the cassandra side wasn't great. If you want to try and improve contributions are always welcome!

**Comment by criccomini** [comment]
See here for Cassandra CDC:

https://github.com/debezium/debezium-incubator/pull/98

**Pull request closed without merging**
